server:
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 90s

myrealtrip:
  ohmyhotel:
    context: consumer

management:
  server:
    port: 9405
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

---
spring:
  config:
    activate:
      on-profile: "local"

logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB
---
spring:
  config:
    activate:
      on-profile:
        - "dev"
        - "dev01"
        - "dev02"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB
---
spring:
  config:
    activate:
      on-profile:
        - "test"
        - "test01"
        - "test02"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB
---
spring:
  config:
    activate:
      on-profile: "stage"
logging:
  level:
    root: warn
    "org.*": warn
    "com.*": warn
    "com.myrealtrip.ohmyhotel.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB

myrealtrip:
  datasource:
    read-write:
      username: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gHugG4tn4H2QWFqB2x7jhWtAAAAcDBuBgkqhkiG9w0BBwagYTBfAgEAMFoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMK7tSFV3sNV7GhPf5AgEQgC09VFk0WdIm4cgUINJ6Lgo7Ci71kBx2A+aobIshM6ll9UWR2Tdg0OKAQWmXg8U=
      password: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gEAELIH2OxZB413drkX73IsAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0MZWPQsOQNzIAD+EAgEQgCv7PRVbP0dNEVzYi+ljJfZrdXZVoDP1bEgozQE1ucnfwbAaMjPnvQx7W1tm
      extra:
        maximum-pool-size: 30
    read-only:
      username: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gHugG4tn4H2QWFqB2x7jhWtAAAAcDBuBgkqhkiG9w0BBwagYTBfAgEAMFoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMK7tSFV3sNV7GhPf5AgEQgC09VFk0WdIm4cgUINJ6Lgo7Ci71kBx2A+aobIshM6ll9UWR2Tdg0OKAQWmXg8U=
      password: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gEAELIH2OxZB413drkX73IsAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0MZWPQsOQNzIAD+EAgEQgCv7PRVbP0dNEVzYi+ljJfZrdXZVoDP1bEgozQE1ucnfwbAaMjPnvQx7W1tm
      extra:
        maximum-pool-size: 30
---
spring:
  config:
    activate:
      on-profile: "prod"
logging:
  level:
    root: warn
    "org.*": warn
    "com.*": warn
    "com.myrealtrip.ohmyhotel.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 14
      total-size-cap: 10GB

myrealtrip:
  datasource:
    read-write:
      username: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gHugG4tn4H2QWFqB2x7jhWtAAAAcDBuBgkqhkiG9w0BBwagYTBfAgEAMFoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMK7tSFV3sNV7GhPf5AgEQgC09VFk0WdIm4cgUINJ6Lgo7Ci71kBx2A+aobIshM6ll9UWR2Tdg0OKAQWmXg8U=
      password: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gEAELIH2OxZB413drkX73IsAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0MZWPQsOQNzIAD+EAgEQgCv7PRVbP0dNEVzYi+ljJfZrdXZVoDP1bEgozQE1ucnfwbAaMjPnvQx7W1tm
      extra:
        maximum-pool-size: 30
    read-only:
      username: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gHugG4tn4H2QWFqB2x7jhWtAAAAcDBuBgkqhkiG9w0BBwagYTBfAgEAMFoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMK7tSFV3sNV7GhPf5AgEQgC09VFk0WdIm4cgUINJ6Lgo7Ci71kBx2A+aobIshM6ll9UWR2Tdg0OKAQWmXg8U=
      password: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gEAELIH2OxZB413drkX73IsAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0MZWPQsOQNzIAD+EAgEQgCv7PRVbP0dNEVzYi+ljJfZrdXZVoDP1bEgozQE1ucnfwbAaMjPnvQx7W1tm
      extra:
        maximum-pool-size: 30
