springdoc:
  swagger-ui:
    path : '/swagger-ui.html'
management:
  server:
    port: 9405
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

myrealtrip:
  ohmyhotel:
    context: api
---
spring:
  config:
    activate:
      on-profile: "local"

logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB
---
spring:
  config:
    activate:
      on-profile:
        - "dev"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB
---
spring:
  config:
    activate:
      on-profile:
        - "dev01"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB
---
spring:
  config:
    activate:
      on-profile:
        - "dev02"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB
---
spring:
  config:
    activate:
      on-profile:
        - "test"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB

---
spring:
  config:
    activate:
      on-profile:
        - "test01"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB

---
spring:
  config:
    activate:
      on-profile:
        - "test02"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB

---
spring:
  config:
    activate:
      on-profile: "stage"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 5
      total-size-cap: 10GB

myrealtrip:
  datasource:
    read-write:
      username:
      password:
      extra:
        maximum-pool-size: 50
    read-only:
      username:
      password:
      extra:
        maximum-pool-size: 50
---
spring:
  config:
    activate:
      on-profile: "prod"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
  file:
    name: /myrealtrip/logs/tomcat/catalina.out
  logback:
    rollingpolicy:
      max-history: 14
      total-size-cap: 10GB

myrealtrip:
  datasource:
    read-write:
      username:
      password:
      extra:
        maximum-pool-size: 50
    read-only:
      username:
      password:
      extra:
        maximum-pool-size: 50