ohmyhotel:
  api:
    base-url: https://dev-api-ota-v2.ohmyhotel.com
    api-key: AQICAHgovqlBdsdUjXt9BbtXP7qgR8K0eyGB9hE6cTsaEEZBAgGBf7XgKOOy/XB2HZhPub6VAAAAlTCBkgYJKoZIhvcNAQcGoIGEMIGBAgEAMHwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM77Rjzioy9v2hv4oHAgEQgE8Op45KVoEKPhiJLcVPgd+g4A577OJAAximrw7AjMAe4n7BmG+bYkjOuHxedJL1OwCIXQy+3orr+nbNabHF426QsbNHDiKDLrQ/lTlYjShV
    secret: AQICAHgovqlBdsdUjXt9BbtXP7qgR8K0eyGB9hE6cTsaEEZBAgFBn7cOfgaMQd1gwxWKFo0KAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhdkgvxVRlNE7QfYUAgEQgCV+YAglHHnNfxw78RkA9B9OSYexjAigTh18k3UfV5zZ+XWacbp0
    health-check:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 10
      response-timeout: 10
      max-in-memory-size: -1
    static-hotel-bulk-list:
      connect-timeout: 10
      write-timeout: 10
      read-timeout: 30
      response-timeout: 30
      max-in-memory-size: -1
    static-hotel-info-list:
      connect-timeout: 10
      write-timeout: 10
      read-timeout: 30
      response-timeout: 30
      max-in-memory-size: -1
    hotels-availability:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 10
      response-timeout: 10
      max-in-memory-size: -1
    rooms-availability:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 10
      response-timeout: 10
      max-in-memory-size: -1
    room-info:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 10
      response-timeout: 10
      max-in-memory-size: -1
    pre-check:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 10
      response-timeout: 10
      max-in-memory-size: -1
    create-booking:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 15
      response-timeout: 15
      max-in-memory-size: -1
    booking-detail:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 15
      response-timeout: 15
      max-in-memory-size: -1

myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.dev-myrealtrip.net
      switching:
        connect-timeout: 5
        write-timeout: 5
        read-timeout: 10
        response-timeout: 10
        max-in-memory-size: -1

---
spring:
  config:
    activate:
      on-profile: "local"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.dev-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "dev"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.dev-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "dev01"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.dev01-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "dev02"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.dev02-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "test"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.test-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "test01"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.test01-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "test02"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.test02-myrealtrip.net
---

spring:
  config:
    activate:
      on-profile: "stage"

ohmyhotel:
  api:
    base-url: https://dev-api-ota-v2.ohmyhotel.com
    api-key:
    secret:

myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.stage-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "prod"

ohmyhotel:
  api:
    base-url: https://dev-api-ota-v2.ohmyhotel.com
    api-key:
    secret:

myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.myrealtrip.net