ohmyhotel:
  api:
    base-url: https://dev-api-ota-v2.ohmyhotel.com
    api-key: AQICAHgovqlBdsdUjXt9BbtXP7qgR8K0eyGB9hE6cTsaEEZBAgGBf7XgKOOy/XB2HZhPub6VAAAAlTCBkgYJKoZIhvcNAQcGoIGEMIGBAgEAMHwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM77Rjzioy9v2hv4oHAgEQgE8Op45KVoEKPhiJLcVPgd+g4A577OJAAximrw7AjMAe4n7BmG+bYkjOuHxedJL1OwCIXQy+3orr+nbNabHF426QsbNHDiKDLrQ/lTlYjShV
    secret: AQICAHgovqlBdsdUjXt9BbtXP7qgR8K0eyGB9hE6cTsaEEZBAgFBn7cOfgaMQd1gwxWKFo0KAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhdkgvxVRlNE7QfYUAgEQgCV+YAglHHnNfxw78RkA9B9OSYexjAigTh18k3UfV5zZ+XWacbp0
    health-check:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 10
      response-timeout: 10
      max-in-memory-size: -1
    static-hotel-bulk-list:
      connect-timeout: 10
      write-timeout: 10
      read-timeout: 30
      response-timeout: 30
      max-in-memory-size: -1
    static-hotel-info-list:
      connect-timeout: 10
      write-timeout: 10
      read-timeout: 30
      response-timeout: 30
      max-in-memory-size: -1
    hotels-availability:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 10
      response-timeout: 10
      max-in-memory-size: -1
    rooms-availability:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 10
      response-timeout: 10
      max-in-memory-size: -1
    room-info:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 10
      response-timeout: 10
      max-in-memory-size: -1
    pre-check:
      connect-timeout: 5
      write-timeout: 5
      read-timeout: 10
      response-timeout: 10
      max-in-memory-size: -1
    create-booking:
      connect-timeout: 30
      write-timeout: 30
      read-timeout: 60
      response-timeout: 60
      max-in-memory-size: -1
    booking-detail:
      connect-timeout: 30
      write-timeout: 30
      read-timeout: 60
      response-timeout: 60
      max-in-memory-size: -1
    cancel-booking:
      connect-timeout: 30
      write-timeout: 30
      read-timeout: 60
      response-timeout: 60
      max-in-memory-size: -1

myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.dev-myrealtrip.net
      switching:
        connect-timeout: 5
        write-timeout: 5
        read-timeout: 10
        response-timeout: 10
        max-in-memory-size: -1
    settle:
      base-url: http://api-settle-v2.dev-myrealtrip.net
      settlement-config:
        conn-timeout: 5
        write-timeout: 5
        read-timeout: 10
        response-timeout: 10
        max-in-memory-size: -1

---
spring:
  config:
    activate:
      on-profile: "local"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.dev-myrealtrip.net
    settle:
      base-url: http://api-settle-v2.dev-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "dev"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.dev-myrealtrip.net
    settle:
      base-url: http://api-settle-v2.dev-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "dev01"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.dev01-myrealtrip.net
    settle:
      base-url: http://api-settle-v2.dev01-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "dev02"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.dev02-myrealtrip.net
    settle:
      base-url: http://api-settle-v2.dev02-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "test"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.test-myrealtrip.net
    settle:
      base-url: http://api-settle-v2.test-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "test01"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.test01-myrealtrip.net
    settle:
      base-url: http://api-settle-v2.test01-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "test02"
myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.test02-myrealtrip.net
    settle:
      base-url: http://api-settle-v2.test02-myrealtrip.net
---

spring:
  config:
    activate:
      on-profile: "stage"

ohmyhotel:
  api: # TODO api-key 세팅 필요
    base-url: https://api-ota-v2.ohmyhotel.com
    api-key: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gHLzGKoz9qyKKhAPYN+JK25AAAAlTCBkgYJKoZIhvcNAQcGoIGEMIGBAgEAMHwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMU3uWAwQRIGYHJTwBAgEQgE8ROc+iZcNYnaNIpnWVUNxr769wCjXFMnkvrLr7xpB2aeaHiYmQRA9fAcJ8nqL3qqB5USMSD9zJ1Ry7zDTtmQdquey46NISsePvlDjcwPBv
    secret: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gGomjPvLS3YF+IjepZWvjnAAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnlSTVwRhz8twZ6LzAgEQgCVe/3ZzP7yUTmSXidxpSrRzNPzwqdPI02Rox/bAZ4pnZXOSofiH

myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.stage-myrealtrip.net
    settle:
      base-url: http://api-settle-v2.stage-myrealtrip.net
---
spring:
  config:
    activate:
      on-profile: "prod"

ohmyhotel:
  api: # TODO api-key 세팅 필요
    base-url: https://api-ota-v2.ohmyhotel.com
    api-key: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gHLzGKoz9qyKKhAPYN+JK25AAAAlTCBkgYJKoZIhvcNAQcGoIGEMIGBAgEAMHwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMU3uWAwQRIGYHJTwBAgEQgE8ROc+iZcNYnaNIpnWVUNxr769wCjXFMnkvrLr7xpB2aeaHiYmQRA9fAcJ8nqL3qqB5USMSD9zJ1Ry7zDTtmQdquey46NISsePvlDjcwPBv
    secret: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gGomjPvLS3YF+IjepZWvjnAAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnlSTVwRhz8twZ6LzAgEQgCVe/3ZzP7yUTmSXidxpSrRzNPzwqdPI02Rox/bAZ4pnZXOSofiH

myrealtrip:
  api:
    unionstay:
      base-url: http://api-unionstay-int.myrealtrip.net
    settle:
      base-url: http://api-settle-v2.myrealtrip.net