myrealtrip:
  ohmyhotel:
    context: batch
spring:
  main:
    lazy-initialization: true

---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
---
spring:
  config:
    activate:
      on-profile: dev, dev01, dev02
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
---
spring:
  config:
    activate:
      on-profile: test, test01, test02
logging:
  level:
    root: info
    "org.*": info
    "com.*": info
---
spring:
  config:
    activate:
      on-profile: "stage"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info

myrealtrip:
  datasource:
    read-write:
      username: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gG5DSXXD7vbONdz2PLNlR5EAAAAbTBrBgkqhkiG9w0BBwagXjBcAgEAMFcGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVJWmE/c4bwTQ2tq+AgEQgCovJoOy81DH3fXHtjQphVShy8HH3AxDqeSSXxGQk4KhUoXCoUbCoknMBJY=
      password: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gEAELIH2OxZB413drkX73IsAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0MZWPQsOQNzIAD+EAgEQgCv7PRVbP0dNEVzYi+ljJfZrdXZVoDP1bEgozQE1ucnfwbAaMjPnvQx7W1tm
      extra:
        maximum-pool-size: 10
    read-only:
      username: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gG5DSXXD7vbONdz2PLNlR5EAAAAbTBrBgkqhkiG9w0BBwagXjBcAgEAMFcGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVJWmE/c4bwTQ2tq+AgEQgCovJoOy81DH3fXHtjQphVShy8HH3AxDqeSSXxGQk4KhUoXCoUbCoknMBJY=
      password: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gEAELIH2OxZB413drkX73IsAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0MZWPQsOQNzIAD+EAgEQgCv7PRVbP0dNEVzYi+ljJfZrdXZVoDP1bEgozQE1ucnfwbAaMjPnvQx7W1tm
      extra:
        maximum-pool-size: 10

---
spring:
  config:
    activate:
      on-profile: "prod"
logging:
  level:
    root: info
    "org.*": info
    "com.*": info

myrealtrip:
  datasource:
    read-write:
      username: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gG5DSXXD7vbONdz2PLNlR5EAAAAbTBrBgkqhkiG9w0BBwagXjBcAgEAMFcGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVJWmE/c4bwTQ2tq+AgEQgCovJoOy81DH3fXHtjQphVShy8HH3AxDqeSSXxGQk4KhUoXCoUbCoknMBJY=
      password: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gEAELIH2OxZB413drkX73IsAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0MZWPQsOQNzIAD+EAgEQgCv7PRVbP0dNEVzYi+ljJfZrdXZVoDP1bEgozQE1ucnfwbAaMjPnvQx7W1tm
      extra:
        maximum-pool-size: 10
    read-only:
      username: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gG5DSXXD7vbONdz2PLNlR5EAAAAbTBrBgkqhkiG9w0BBwagXjBcAgEAMFcGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVJWmE/c4bwTQ2tq+AgEQgCovJoOy81DH3fXHtjQphVShy8HH3AxDqeSSXxGQk4KhUoXCoUbCoknMBJY=
      password: AQICAHjBvCRGPyjOz/X2af580VjoYm0zdHIUQQJDmVzX7G9C6gEAELIH2OxZB413drkX73IsAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0MZWPQsOQNzIAD+EAgEQgCv7PRVbP0dNEVzYi+ljJfZrdXZVoDP1bEgozQE1ucnfwbAaMjPnvQx7W1tm
      extra:
        maximum-pool-size: 10